server:
  bind_address:
  mode:
  amqp_mode:

database:
  host:
  port:
  user:
  password:
  dbname:

jwt:
  secret:

mq:
  url:
  queues:
    - name: review-file-diffs
      durable: true
      auto_delete: false
      exclusive: false
      no_wait: false
      args:

pubsub:
  project_id:
  topics:
    - review-file-diffs
